
name: Copiar Archivos

on:
  push:
    branches:
      - main

jobs:
  copy-files:
    runs-on: ubuntu-latest

    steps:
      - name: Verificar Existencia del Directorio de Origen
        run: test -d  "gafservice/A&A_GAF_Tarea02" && echo "El directorio existe" || echo "El directorio no existe"
   
      - name: Configurar Usuario de Git (Solo si el repositorio existe)
        run: |
          if [ -d .git ]; then
            git config --global user.name "GitHub Actions"
            git config --global user.email "actions@github.com"
          else
            echo "No se encontró un repositorio de Git."
          fi

      - name: Copiar Archivos
        run: |
          if [ -d A\&A_GAF_HW02/HW02/ ]; then
            mkdir -p Octave/AprenAuto/HW02
            cp -r gafservice/A-A_GAF_Tarea02/ Octave/AprenAuto/HW02/
          else
            echo "El directorio de origen no existe o está vacío."
          fi

      - name: Añadir y Hacer Commit de los Cambios
        run: |
          if [ -d .git ]; then
            git add Octave/AprenAuto/HW02/*
            git commit -m "Copia de archivos realizada por GitHub Actions"
            git push origin main
          else
            echo "No se encontró un repositorio de Git, no se realizarán commits ni push."
          fi


   
