name: Copiar Archivos

on:
  push:
    branches:
      - main

jobs:
  copy-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repositorio
        uses: actions/checkout@v2

      - name: Copiar Archivos
        run: |
          # Lógica para copiar archivos
          # cp -r A&A_GAF_HW02/HW02 Octave/AprenAuto/HW02
          mv A&A_GAF_HW02/HW02/* Octave/AprenAuto/HW02/

      - name: Commit y Push Cambios
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@users.noreply.github.com"
          git add .
          git commit -m "Copia de archivos realizada por GitHub Actions"
          git push
