 name: Copiar Archivos

on:
  push:
    branches:
      - main

jobs:
  copy-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repositorio
        uses: actions/checkout@v2

      - name: Copiar Archivos
        run: |
          shopt -s dotglob
          mv A\&A_GAF_HW02/HW02/* Octave/AprenAuto/HW02/
          shopt -u dotglob

      - name: Añadir y Hacer Commit de los Cambios
        run: |
          git add Octave/AprenAuto/HW02/*
          git commit -m "Copia de archivos realizada por GitHub Actions"
          git push
   
